### ISSUE TITLE
Simple .sfn misconfiguration issue?

### ISSUE THREAD

**Issue by donbecker** [sparkleformation/sparkle_formation#199]
Trying to get up and running with SFN but cannot seem to get the configuration for AWS right. 

Windows 7
sparkle_formation 3.0.10
bundler 1.13.6
miasma-aws 0.3.2

Following the guide here: 
[http://www.sparkleformation.io/docs/guides/getting-started.html#configuration](url)

```
PS> bundle exec sfn conf
[Sfn]: Current configuration state:
  apply_nesting: deep
  colors: true
  credentials:
    provider: aws
  file_path_prompt: true
  interactive_parameters: true
  merge_api_options: false
  options:
    capabilities:
      CAPABILITY_IAM
    notification_topics:
    on_failure: nothing
    tags:
      creator: Don
  parameter_validation: default
  plan: true
  plan_only: false
  poll: true
  processing: true
```

I believe I'm in the correct directory ("sparkle-guide"). 

I've edited the generated .sfn file, here are the contents: 

```ruby
# This is an auto-generated configuration file for
# the sfn CLI. To view all available configuration
# options, please see:
# http://www.sparkleformation.io/docs/sfn/configuration.html
Configuration.new do
  #   Set style of stack nesting
  apply_nesting 'deep'
  #   Enable processing of SparkleFormation templates
  processing true
  #   Provider specific options used when creating
  #   new stacks. Options defined here are AWS specific.
  options do
    on_failure 'nothing'
    notification_topics []
    capabilities ['CAPABILITY_IAM']
    tags do
      creator ENV['USER']
    end
  end
  #   Name of bucket in object store to hold nested
  #   stack templates
  # nesting_bucket 'BUCKET_NAME'
  #   Prefix used on generated template path prior to storage
  #   in the object store
  # nesting_prefix 'nested-templates'
  #   Remote provider credentials
  credentials do
    #  Remote provider name (:aws, :azure, :google, :open_stack, :rackspace)
    provider :aws
    #  AWS credentials information
    aws_access_key_id ENV['AKIA...........']
    aws_secret_access_key ENV['9g5...........']
    aws_region ENV['us-west-2']
    aws_bucket_region ENV['us-west-2']
    # aws_sts_role_arn ENV['AWS_STS_ROLE_ARN']
    #  Eucalyptus related additions
    # api_endpoint ENV['EUCA_ENDPOINT']
    # euca_compat 'path'
    # ssl_enabled false
    #  Azure credentials information
    azure_tenant_id ENV['AZURE_TENANT_ID']
    azure_client_id ENV['AZURE_CLIENT_ID']
    azure_subscription_id ENV['AZURE_SUBSCRIPTION_ID']
    azure_client_secret ENV['AZURE_CLIENT_SECRET']
    azure_region ENV['AZURE_REGION']
    azure_blob_account_name ENV['AZURE_BLOB_ACCOUNT_NAME']
    azure_blob_secret_key ENV['AZURE_BLOB_SECRET_KEY']
    #  Defaults to "miasma-orchestration-templates"
    azure_root_orchestration_container ENV['AZURE_ROOT_ORCHESTRATION_CONTAINER']
    #  OpenStack credentials information
    open_stack_identity_url ENV['OPENSTACK_IDENTITY_URL']
    open_stack_username ENV['OPENSTACK_USERNAME']
    open_stack_user_id ENV['OPENSTACK_USER_ID']
    open_stack_password ENV['OPENSTACK_PASSWORD']
    open_stack_token ENV['OPENSTACK_TOKEN']
    open_stack_region ENV['OPENSTACK_REGION']
    open_stack_tenant_name ENV['OPENSTACK_TENANT_NAME']
    open_stack_domain ENV['OPENSTACK_DOMAIN']
    open_stack_project ENV['OPENSTACK_PROJECT']
    #  Rackspace credentials information
    rackspace_api_key ENV['RACKSPACE_API_KEY']
    rackspace_username ENV['RACKSPACE_USERNAME']
    rackspace_region ENV['RACKSPACE_REGION']
    #  Google Cloud Deployment Manager credentials
    google_service_account_email ENV['GOOGLE_SERVICE_ACCOUNT_EMAIL']
    google_service_account_private_key ENV['GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY']
    google_project ENV['GOOGLE_PROJECT']
  end
end
```

Can anyone experienced with SFN tell me what might be incorrect? 

Trying the config test in the guide:

```
PS> bundle exec sfn list

[ERROR]: Failed to create remote API connection. Please validate configuration!
[ERROR]: Connection failure reason - ArgumentError - Missing required option: `aws_access_key_id`
ERROR: ArgumentError: Missing required option: `aws_access_key_id`
```

If I navigate up one level, I get a different error, which makes me suspect that SFN "sees" the .sfn config file: 

```
PS> bundle exec sfn list

Could not locate Gemfile or .bundle/ directory
```
