### ISSUE TITLE
Arrays in resource properties not handled the same as other properties

### ISSUE THREAD

**Issue by rabidscorpio** [sparkleformation/sparkle_formation#91]
Sparkleformation 1.1 seems to have introduced a bug where any time an array is passed into the properties of a resource, the keys don't get converted to camelcase like all the other property keys. We can use camel case in this case but it would be nice if all the keys were treated the same way.

**Comment by chrisroberts** [comment]
Do you have a code snippet you could provide showing the array usage you're describing? Thanks!

**Comment by rabidscorpio** [comment]
To give you an example, we pass hashes as the properties block for dynamic resources. The hashes are actually in yaml config files that get imported. So in the following example, the ```health_check``` section works fine, the keys get converted into camelcase which is what the old version used to do. The second section, however, does not have that same conversion so the keys need to be put into camelcase from the start in order for a template to be processed correctly.
```
health_check:
  healthy_threshold: 10
  interval: 6
  target: TCP:80
  timeout: 5
  unhealthy_threshold: 2
listeners:
  - InstancePort: 80
    InstanceProtocol: TCP
    Protocol: TCP
    LoadBalancerPort: 80
```

Another example with a hash created in the template:
```
  dynamic!(:aws_ec2_instance, "TestInstance", {
    :availability_zone             => "us-east-1b",
    :disable_api_termination       => "false",
    :security_group_ids            => default_security_groups,
    :subnet_id                     => subnets.first,
    :tags                          => [{
      :Key                           => 'Name',
      :Value                         => "TestInstance",
    }, {
      :Key                           => 'Environment',
      :Value                         => "Testing",
    }]
  )
```
In this case, the tags are in an array and therefore don't automatically get converted to camelcase which is why they're capitalized in this example. All the other keys get converted to camelcase, though.
